### Importing the Required Libraries:-

In [1]:
import selenium
from selenium import webdriver
import time
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.common.exceptions import NoSuchElementException

### Opening the Driver:-

In [2]:
driver = webdriver.Chrome('chromedriver.exe')

### Giving the URL:-

In [3]:
url="https://www.makemytrip.com/flight/search?itinerary=DEL-BLR-23/04/2022&tripType=O&paxType=A-1_C-0_I-0&intl=false&cabinClass=E&ccde=IN&lang=eng"
driver.get(url)
time.sleep(2)
ad=driver.find_element_by_xpath('//div[@class="overlay"]/div/span').click()
time.sleep(2)
btn=driver.find_element_by_xpath('/html/body/div/div/div[2]/div[2]/div/div[2]/div[2]/div[3]/div/div/div/div[1]/div[2]/div/div[1]/div[2]/div[4]/div/button').click()
time.sleep(2)
for i in range(1000):
    driver.execute_script("window.scrollBy(0,1000)")

In [6]:
Airline=[]
source=[]
destination=[]
Arival=[]
Departure=[]
no_of_stops=[]
prices=[]

name=driver.find_elements_by_xpath('//div[@class="makeFlex align-items-center  "]/span')
for i in name:
    Airline.append(i.text)
    
so=driver.find_elements_by_xpath('//div[@class="makeFlex flex-column flightTimeInfo"]/p[2]')
for i in range(len(so)):
    if i%2==0:
        source.append(so[i].text)
    else:
        destination.append(so[i].text)
        
ti=driver.find_elements_by_xpath('//div[@class="makeFlex flex-column flightTimeInfo"]/p/span')
for i in range(len(ti)):
    if i%2==0:
        Arival.append(ti[i].text)
    else:
        Departure.append(ti[i].text)
        
st=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/div/p')
for i in st:
    if i.text[0]!='N':
        no_of_stops.append(int(i.text[0]))
    else:
        no_of_stops.append(int('0'))

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]/p')
for i in price:
    prices.append(i.text.replace('â‚¹',''))

print(len(Airline))
print(len(source))
print(len(destination))
print(len(Arival))
print(len(Departure))
print(len(no_of_stops))
print(len(prices))

59
59
59
59
59
59
59

In [7]:
df= pd.DataFrame({"Airlines_Name":Airline,
                 "Date Of Journey":"23-Apr-2022",
                 "Source":source,
                 "Destination":destination,
                 "Arival":Arival,
                 "Departure":Departure,
                 "No. Of Stoppage":no_of_stops,
                 "Price":prices})

df

,Airlines_Name,Date Of Journey,Source,Destination,Arival,Departure,No. Of Stoppage,Price
0,Go First,23-Apr-2022,New Delhi,Bengaluru,02:40,07:45,1,"8,159"
1,Go First,23-Apr-2022,New Delhi,Bengaluru,12:35,20:55,1,"8,159"
2,Go First,23-Apr-2022,New Delhi,Bengaluru,11:30,20:55,1,"8,159"
3,Go First,23-Apr-2022,New Delhi,Bengaluru,15:45,21:45,1,"8,159"
4,Go First,23-Apr-2022,New Delhi,Bengaluru,14:00,21:45,1,"8,159"
5,Go First,23-Apr-2022,New Delhi,Bengaluru,13:10,21:45,1,"8,159"
6,SpiceJet,23-Apr-2022,New Delhi,Bengaluru,14:55,22:30,1,"8,159"
7,IndiGo,23-Apr-2022,New Delhi,Bengaluru,18:00,23:40,1,"8,159"
8,IndiGo,23-Apr-2022,New Delhi,Bengaluru,15:00,23:40,1,"8,159"
9,IndiGo,23-Apr-2022,New Delhi,Bengaluru,13:25,23:40,1,"8,159"
10,IndiGo,23-Apr-2022,New Delhi,Bengaluru,19:30,00:50,1,"8,159"
11,Go First,23-Apr-2022,New Delhi,Bengaluru,22:45,07:45,1,"8,159"
12,AirAsia,23-Apr-2022,New Delhi,Bengaluru,06:05,13:00,1,"8,346"
13,AirAsia,23-Apr-2022,New Delhi,Bengaluru,10:00,17:30,1,"8,346"
14,AirAsia,23-Apr-2022,New Delhi,Bengaluru,13:00,20:05,1,"8,346"
15,AirAsia,23-Apr-2022,New Delhi,Bengaluru,16:15,22:25,2,"8,346"
16,SpiceJet,23-Apr-2022,New Delhi,Bengaluru,15:10,21:50,1,"8,789"
17,IndiGo,23-Apr-2022,New Delhi,Bengaluru,23:20,06:05,1,"9,367"
18,IndiGo,23-Apr-2022,New Delhi,Bengaluru,05:50,08:35,0,"9,682"
19,IndiGo,23-Apr-2022,New Delhi,Bengaluru,02:25,05:15,0,"9,997"
20,IndiGo,23-Apr-2022,New Delhi,Bengaluru,03:50,06:40,0,"9,997"
21,Air India,23-Apr-2022,New Delhi,Bengaluru,06:10,08:55,0,"10,050"
22,Vistara,23-Apr-2022,New Delhi,Bengaluru,06:15,09:00,0,"10,050"
23,Go First,23-Apr-2022,New Delhi,Bengaluru,05:50,08:35,0,"10,104"
24,SpiceJet,23-Apr-2022,New Delhi,Bengaluru,06:05,09:00,0,"10,259"
25,IndiGo,23-Apr-2022,New Delhi,Bengaluru,06:55,09:50,0,"10,417"
26,AirAsia,23-Apr-2022,New Delhi,Bengaluru,14:55,22:55,1,"10,686"
27,IndiGo,23-Apr-2022,New Delhi,Bengaluru,22:55,01:45,0,"10,837"
28,SpiceJet,23-Apr-2022,New Delhi,Bengaluru,21:25,00:05,0,"10,889"
29,IndiGo,23-Apr-2022,New Delhi,Bengaluru,06:40,13:10,1,"11,178"
30,IndiGo,23-Apr-2022,New Delhi,Bengaluru,21:30,00:15,0,"11,519"
31,AirAsia,23-Apr-2022,New Delhi,Bengaluru,21:40,00:30,0,"11,519"
32,IndiGo,23-Apr-2022,New Delhi,Bengaluru,01:50,08:15,1,"11,939"
33,Air India,23-Apr-2022,New Delhi,Bengaluru,17:15,20:15,0,"12,360"
34,IndiGo,23-Apr-2022,New Delhi,Bengaluru,12:55,18:50,1,"12,837"
35,Go First,23-Apr-2022,New Delhi,Bengaluru,20:30,23:20,0,"13,284"
36,IndiGo,23-Apr-2022,New Delhi,Bengaluru,20:10,23:00,0,"13,304"
37,Vistara,23-Apr-2022,New Delhi,Bengaluru,20:40,23:20,0,"13,305"
38,IndiGo,23-Apr-2022,New Delhi,Bengaluru,15:15,20:30,1,"13,357"
39,IndiGo,23-Apr-2022,New Delhi,Bengaluru,08:20,11:00,0,"14,354"
40,IndiGo,23-Apr-2022,New Delhi,Bengaluru,17:25,19:55,0,"14,354"
41,Go First,23-Apr-2022,New Delhi,Bengaluru,10:40,15:05,1,"14,612"
42,IndiGo,23-Apr-2022,New Delhi,Bengaluru,09:15,11:55,0,"14,875"
43,IndiGo,23-Apr-2022,New Delhi,Bengaluru,15:20,18:15,0,"14,875"
44,IndiGo,23-Apr-2022,New Delhi,Bengaluru,18:30,21:15,0,"14,875"
45,AirAsia,23-Apr-2022,New Delhi,Bengaluru,08:10,10:40,0,"14,879"
46,AirAsia,23-Apr-2022,New Delhi,Bengaluru,09:35,12:25,0,"14,879"
47,AirAsia,23-Apr-2022,New Delhi,Bengaluru,18:45,21:40,0,"14,879"
48,IndiGo,23-Apr-2022,New Delhi,Bengaluru,13:00,15:35,0,"15,719"
49,AirAsia,23-Apr-2022,New Delhi,Bengaluru,21:00,23:50,0,"15,751"
50,Vistara,23-Apr-2022,New Delhi,Bengaluru,08:05,10:50,0,"16,770"
51,Vistara,23-Apr-2022,New Delhi,Bengaluru,16:05,18:50,0,"16,770"
52,Vistara,23-Apr-2022,New Delhi,Bengaluru,19:50,22:40,0,"16,770"
53,IndiGo,23-Apr-2022,New Delhi,Bengaluru,11:30,14:15,0,"17,504"
54,Vistara,23-Apr-2022,New Delhi,Bengaluru,09:05,11:50,0,"20,340"
55,Air India,23-Apr-2022,New Delhi,Bengaluru,09:45,12:30,0,"20,340"
56,Air India,23-Apr-2022,New Delhi,Bengaluru,13:30,16:15,0,"20,340"
57,Vistara,23-Apr-2022,New Delhi,Bengaluru,17:35,20:25,0,"20,340"
58,Air India,23-Apr-2022,New Delhi,Bengaluru,21:50,00:40,0,"20,340"

In [8]:
url="https://www.makemytrip.com/flight/search?itinerary=BLR-DEL-23/04/2022&tripType=O&paxType=A-1_C-0_I-0&intl=false&cabinClass=E&ccde=IN&lang=eng"
driver.get(url)
time.sleep(2)
for i in range(200):
    driver.execute_script("window.scrollBy(0,1000)")

In [9]:
Airline=[]
source=[]
destination=[]
Arival=[]
Departure=[]
no_of_stops=[]
prices=[]

name=driver.find_elements_by_xpath('//div[@class="makeFlex align-items-center  "]/span')
for i in name:
    Airline.append(i.text)
    
so=driver.find_elements_by_xpath('//div[@class="makeFlex flex-column flightTimeInfo"]/p[2]')
for i in range(len(so)):
    if i%2==0:
        source.append(so[i].text)
    else:
        destination.append(so[i].text)
        
ti=driver.find_elements_by_xpath('//div[@class="makeFlex flex-column flightTimeInfo"]/p/span')
for i in range(len(ti)):
    if i%2==0:
        Arival.append(ti[i].text)
    else:
        Departure.append(ti[i].text)
        
st=driver.find_elements_by_xpath('//div[@class="stop-info flexOne"]/div/p')
for i in st:
    if i.text[0]!='N':
        no_of_stops.append(int(i.text[0]))
    else:
        no_of_stops.append(int('0'))

price=driver.find_elements_by_xpath('//div[@class="textRight flexOne"]/p')
for i in price:
    prices.append(i.text.replace('â‚¹',''))

print(len(Airline))
print(len(source))
print(len(destination))
print(len(Arival))
print(len(Departure))
print(len(no_of_stops))
print(len(prices))

47
47
47
47
47
47
47

In [10]:
df1= pd.DataFrame({"Airlines_Name":Airline,
                 "Date Of Journey":"23-Apr-2022",
                 "Source":source,
                 "Destination":destination,
                 "Arival":Arival,
                 "Departure":Departure,
                 "No. Of Stoppage":no_of_stops,
                 "Price":prices})

df1

,Airlines_Name,Date Of Journey,Source,Destination,Arival,Departure,No. Of Stoppage,Price
0,IndiGo,23-Apr-2022,Bengaluru,New Delhi,20:30,23:15,0,"8,419"
1,SpiceJet,23-Apr-2022,Bengaluru,New Delhi,21:10,23:45,0,"8,419"
2,Go First,23-Apr-2022,Bengaluru,New Delhi,21:30,00:15,0,"8,419"
3,Air India,23-Apr-2022,Bengaluru,New Delhi,21:30,00:30,0,"8,419"
4,IndiGo,23-Apr-2022,Bengaluru,New Delhi,22:00,00:45,0,"8,419"
5,AirAsia,23-Apr-2022,Bengaluru,New Delhi,22:30,01:20,0,"8,419"
6,IndiGo,23-Apr-2022,Bengaluru,New Delhi,23:10,02:00,0,"8,419"
7,Go First,23-Apr-2022,Bengaluru,New Delhi,08:15,16:50,1,"8,419"
8,IndiGo,23-Apr-2022,Bengaluru,New Delhi,04:40,07:25,0,"8,892"
9,SpiceJet,23-Apr-2022,Bengaluru,New Delhi,16:35,22:50,1,"9,049"
10,SpiceJet,23-Apr-2022,Bengaluru,New Delhi,18:10,00:05,1,"9,049"
11,Vistara,23-Apr-2022,Bengaluru,New Delhi,21:15,23:50,0,"9,259"
12,IndiGo,23-Apr-2022,Bengaluru,New Delhi,06:00,08:45,0,"9,312"
13,Go First,23-Apr-2022,Bengaluru,New Delhi,04:45,07:40,0,"9,469"
14,AirAsia,23-Apr-2022,Bengaluru,New Delhi,09:00,14:20,1,"9,679"
15,AirAsia,23-Apr-2022,Bengaluru,New Delhi,13:40,19:20,1,"9,679"
16,IndiGo,23-Apr-2022,Bengaluru,New Delhi,00:45,03:30,0,"9,942"
17,IndiGo,23-Apr-2022,Bengaluru,New Delhi,11:45,14:40,0,"9,942"
18,IndiGo,23-Apr-2022,Bengaluru,New Delhi,19:15,22:00,0,"9,942"
19,Air India,23-Apr-2022,Bengaluru,New Delhi,06:10,08:55,0,"10,309"
20,SpiceJet,23-Apr-2022,Bengaluru,New Delhi,05:55,08:35,0,"10,519"
21,IndiGo,23-Apr-2022,Bengaluru,New Delhi,18:00,20:45,0,"10,603"
22,IndiGo,23-Apr-2022,Bengaluru,New Delhi,15:35,21:55,1,"11,438"
23,IndiGo,23-Apr-2022,Bengaluru,New Delhi,12:35,18:35,1,"12,147"
24,IndiGo,23-Apr-2022,Bengaluru,New Delhi,07:45,10:40,0,"12,304"
25,IndiGo,23-Apr-2022,Bengaluru,New Delhi,13:55,16:40,0,"12,304"
26,IndiGo,23-Apr-2022,Bengaluru,New Delhi,14:55,17:45,0,"12,304"
27,Vistara,23-Apr-2022,Bengaluru,New Delhi,18:50,21:35,0,"12,304"
28,Vistara,23-Apr-2022,Bengaluru,New Delhi,19:40,22:25,0,"12,304"
29,IndiGo,23-Apr-2022,Bengaluru,New Delhi,08:50,15:20,1,"12,514"
30,AirAsia,23-Apr-2022,Bengaluru,New Delhi,00:25,03:20,0,"13,141"
31,AirAsia,23-Apr-2022,Bengaluru,New Delhi,18:15,21:10,0,"13,141"
32,Go First,23-Apr-2022,Bengaluru,New Delhi,06:00,11:05,1,"13,321"
33,Vistara,23-Apr-2022,Bengaluru,New Delhi,07:00,09:40,0,"13,564"
34,IndiGo,23-Apr-2022,Bengaluru,New Delhi,09:20,12:10,0,"13,564"
35,IndiGo,23-Apr-2022,Bengaluru,New Delhi,16:30,19:15,0,"13,564"
36,Vistara,23-Apr-2022,Bengaluru,New Delhi,17:45,20:20,0,"13,564"
37,Air India,23-Apr-2022,Bengaluru,New Delhi,13:20,15:40,0,"13,774"
38,IndiGo,23-Apr-2022,Bengaluru,New Delhi,07:10,12:10,1,"13,879"
39,"Star Air, IndiGo",23-Apr-2022,Bengaluru,New Delhi,07:05,13:55,1,"14,568"
40,Vistara,23-Apr-2022,Bengaluru,New Delhi,08:00,10:40,0,"15,139"
41,Vistara,23-Apr-2022,Bengaluru,New Delhi,09:45,12:40,0,"15,139"
42,Air India,23-Apr-2022,Bengaluru,New Delhi,10:00,12:50,0,"15,349"
43,Air India,23-Apr-2022,Bengaluru,New Delhi,17:00,19:50,0,"15,349"
44,Vistara,23-Apr-2022,Bengaluru,New Delhi,11:30,14:10,0,"17,029"
45,AirAsia,23-Apr-2022,Bengaluru,New Delhi,06:10,08:55,0,"20,598"
46,AirAsia,23-Apr-2022,Bengaluru,New Delhi,11:15,13:55,0,"20,598"

In [11]:
tdf = pd.concat([df,df1],axis = 0, ignore_index=True)
tdf

,Airlines_Name,Date Of Journey,Source,Destination,Arival,Departure,No. Of Stoppage,Price
0,Go First,23-Apr-2022,New Delhi,Bengaluru,02:40,07:45,1,"8,159"
1,Go First,23-Apr-2022,New Delhi,Bengaluru,12:35,20:55,1,"8,159"
2,Go First,23-Apr-2022,New Delhi,Bengaluru,11:30,20:55,1,"8,159"
3,Go First,23-Apr-2022,New Delhi,Bengaluru,15:45,21:45,1,"8,159"
4,Go First,23-Apr-2022,New Delhi,Bengaluru,14:00,21:45,1,"8,159"
...,...,...,...,...,...,...,...,...
101,Air India,23-Apr-2022,Bengaluru,New Delhi,10:00,12:50,0,"15,349"
102,Air India,23-Apr-2022,Bengaluru,New Delhi,17:00,19:50,0,"15,349"
103,Vistara,23-Apr-2022,Bengaluru,New Delhi,11:30,14:10,0,"17,029"
104,AirAsia,23-Apr-2022,Bengaluru,New Delhi,06:10,08:55,0,"20,598"
105,AirAsia,23-Apr-2022,Bengaluru,New Delhi,11:15,13:55,0,"20,598"

In [12]:
tdf.to_csv("Flight_Price.csv")